global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    metrics_path: '/metrics'
    scrape_interval: 5s  
    static_configs:
      - targets: ['cadvisor:8081']

  - job_name: 'prom-gateway'
    metrics_path: '/metrics'
    scrape_interval: 5s  
    static_configs:
      - targets: ['prom-gateway:9091']   
